SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


INSERT INTO `channels` (`id`, `lang`, `title`, `order`) VALUES
(1, 'en', 'questions & answers', 0),
(1, 'fr', 'questions & réponses', 0),
(1, 'nl', 'vragen & antwoorden', 0),
(2, 'en', 'observations', 0),
(2, 'fr', 'observations', 0),
(2, 'nl', 'observaties', 0),
(3, 'en', 'tips & advice', 0),
(3, 'fr', 'conseils & astuces', 0),
(3, 'nl', 'tips', 0),
(4, 'en', 'garden pests & diseases', 0),
(4, 'fr', 'pestes & maladies du jardin', 0),
(4, 'nl', 'tuin plagen & ziekten', 0),
(5, 'en', 'harvest', 0),
(5, 'fr', 'récolte', 0),
(5, 'nl', 'oogst', 0),
(6, 'en', 'funny', 6),
(6, 'fr', 'amusant', 6),
(6, 'nl', 'grappig', 6);

INSERT INTO `channel_tags` (`channel_id`, `tag_id`) VALUES
(3, 3),
(3, 4),
(3, 5),
(3, 6),
(4, 7),
(4, 8),
(4, 9),
(4, 10),
(4, 11),
(2, 12),
(2, 13),
(2, 14),
(1, 15),
(1, 16),
(1, 17),
(1, 18),
(1, 19),
(1, 20),
(1, 21),
(5, 22),
(5, 23),
(3, 24),
(3, 25),
(3, 26),
(3, 27),
(5, 28),
(2, 32),
(5, 33),
(3, 34),
(6, 35);

INSERT INTO `locale` (`code`, `group`, `english`, `native`, `most_used`, `interface`) VALUES
('aa', 'Afro-Asiatic', 'Afar', 'Afaraf', 0, 0),
('ab', 'Northwest Caucasian', 'Abkhaz', 'аҧсуа бызшәа - аҧсшәа', 0, 0),
('ae', 'Indo-European', 'Avestan', 'avesta', 0, 0),
('af', 'Indo-European', 'Afrikaans', 'Afrikaans', 0, 0),
('ak', 'Niger–Congo', 'Akan', 'Akan', 0, 0),
('am', 'Afro-Asiatic', 'Amharic', 'አማርኛ', 0, 0),
('an', 'Indo-European', 'Aragonese', 'aragonés', 0, 0),
('ar', 'Afro-Asiatic', 'Arabic', 'العربية', 0, 0),
('as', 'Indo-European', 'Assamese', 'অসমীয়া', 0, 0),
('av', 'Northeast Caucasian', 'Avaric', 'авар мацӀ - магӀарул мацӀ', 0, 0),
('ay', 'Aymaran', 'Aymara', 'aymar aru', 0, 0),
('az', 'Turkic', 'South Azerbaijani', 'تورکجه‎', 0, 0),
('ba', 'Turkic', 'Bashkir', 'башҡорт теле', 0, 0),
('be', 'Indo-European', 'Belarusian', 'беларуская мова', 0, 0),
('bg', 'Indo-European', 'Bulgarian', 'български език', 0, 0),
('bh', 'Indo-European', 'Bihari', 'भोजपुरी', 0, 0),
('bi', 'Creole', 'Bislama', 'Bislama', 0, 0),
('bm', 'Niger–Congo', 'Bambara', 'bamanankan', 0, 0),
('bn', 'Indo-European', 'Bengali - Bangla', 'বাংলা', 0, 0),
('br', 'Indo-European', 'Breton', 'brezhoneg', 0, 0),
('bs', 'Indo-European', 'Bosnian', 'bosanski jezik', 0, 0),
('ca', 'Indo-European', 'Catalan - Valencian', 'català - valencià', 1, 0),
('ce', 'Northeast Caucasian', 'Chechen', 'нохчийн мотт', 0, 0),
('ch', 'Austronesian', 'Chamorro', 'Chamoru', 0, 0),
('co', 'Indo-European', 'Corsican', 'corsu', 0, 0),
('cr', 'Algonquian', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 0, 0),
('cs', 'Indo-European', 'Czech', 'čeština - český jazyk', 0, 0),
('cv', 'Turkic', 'Chuvash', 'чӑваш чӗлхи', 0, 0),
('cy', 'Indo-European', 'Welsh', 'Cymraeg', 0, 0),
('da', 'Indo-European', 'Danish', 'dansk', 0, 0),
('de', 'Indo-European', 'German', 'Deutsch', 1, 0),
('dv', 'Indo-European', 'Divehi - Dhivehi - Maldivian', 'ދިވެހި', 0, 0),
('ee', 'Niger–Congo', 'Ewe', 'Eʋegbe', 0, 0),
('el', 'Indo-European', 'Greek (modern)', 'ελληνικά', 0, 0),
('en', 'Indo-European', 'English', 'English', 1, 1),
('es', 'Indo-European', 'Spanish - Castilian', 'español - castellano', 1, 0),
('et', 'Uralic', 'Estonian', 'eesti - eesti keel', 0, 0),
('eu', 'Language isolate', 'Basque', 'euskara - euskera', 0, 0),
('fa', 'Indo-European', 'Persian (Farsi)', 'فارسی', 0, 0),
('ff', 'Niger–Congo', 'Fula - Fulah - Pulaar - Pular', 'Fulfulde - Pulaar - Pular', 0, 0),
('fi', 'Uralic', 'Finnish', 'suomi - suomen kieli', 0, 0),
('fj', 'Austronesian', 'Fijian', 'vosa Vakaviti', 0, 0),
('fo', 'Indo-European', 'Faroese', 'føroyskt', 0, 0),
('fr', 'Indo-European', 'French', 'français', 1, 1),
('fy', 'Indo-European', 'Western Frisian', 'Frysk', 0, 0),
('ga', 'Indo-European', 'Irish', 'Gaeilge', 0, 0),
('gd', 'Indo-European', 'Scottish Gaelic - Gaelic', 'Gàidhlig', 0, 0),
('gl', 'Indo-European', 'Galician', 'galego', 0, 0),
('gn', 'Tupian', 'Guaraní', 'Avañe''ẽ', 0, 0),
('gu', 'Indo-European', 'Gujarati', 'ગુજરાતી', 0, 0),
('gv', 'Indo-European', 'Manx', 'Gaelg - Gailck', 0, 0),
('ha', 'Afro-Asiatic', 'Hausa', 'Hausa - هَوُسَ', 0, 0),
('he', 'Afro-Asiatic', 'Hebrew (modern)', 'עברית', 0, 0),
('hi', 'Indo-European', 'Hindi', 'हिन्दी - हिंदी', 0, 0),
('ho', 'Austronesian', 'Hiri Motu', 'Hiri Motu', 0, 0),
('hr', 'Indo-European', 'Croatian', 'hrvatski jezik', 0, 0),
('ht', 'Creole', 'Haitian', 'Kreyòl ayisyen', 0, 0),
('hu', 'Uralic', 'Hungarian', 'magyar', 0, 0),
('hy', 'Indo-European', 'Armenian', 'Հայերեն', 0, 0),
('hz', 'Niger–Congo', 'Herero', 'Otjiherero', 0, 0),
('id', 'Austronesian', 'Indonesian', 'Bahasa Indonesia', 0, 0),
('ig', 'Niger–Congo', 'Igbo', 'Asụsụ Igbo', 0, 0),
('ik', 'Eskimo–Aleut', 'Inupiaq', 'Iñupiaq - Iñupiatun', 0, 0),
('is', 'Indo-European', 'Icelandic', 'Íslenska', 0, 0),
('it', 'Indo-European', 'Italian', 'italiano', 1, 0),
('iu', 'Eskimo–Aleut', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 0, 0),
('ja', 'Japonic', 'Japanese', '日本語 (にほんご)', 1, 0),
('jv', 'Austronesian', 'Javanese', 'basa Jawa', 0, 0),
('ka', 'South Caucasian', 'Georgian', 'ქართული', 0, 0),
('kg', 'Niger–Congo', 'Kongo', 'KiKongo', 0, 0),
('ki', 'Niger–Congo', 'Kikuyu - Gikuyu', 'Gĩkũyũ', 0, 0),
('kj', 'Niger–Congo', 'Kwanyama - Kuanyama', 'Kuanyama', 0, 0),
('kk', 'Turkic', 'Kazakh', 'қазақ тілі', 0, 0),
('kl', 'Eskimo–Aleut', 'Kalaallisut - Greenlandic', 'kalaallisut - kalaallit oqaasii', 0, 0),
('km', 'Austroasiatic', 'Khmer', 'ខ្មែរ - ខេមរភាសា - ភាសាខ្មែរ', 0, 0),
('kn', 'Dravidian', 'Kannada', 'ಕನ್ನಡ', 0, 0),
('ko', 'Language isolate', 'Korean', '한국어 (韓國語) - 조선어 (朝鮮語)', 0, 0),
('kr', 'Nilo-Saharan', 'Kanuri', 'Kanuri', 0, 0),
('ks', 'Indo-European', 'Kashmiri', 'कश्मीरी - كشميري‎', 0, 0),
('ku', 'Indo-European', 'Kurdish', 'Kurdî - كوردی‎', 0, 0),
('kv', 'Uralic', 'Komi', 'коми кыв', 0, 0),
('kw', 'Indo-European', 'Cornish', 'Kernewek', 0, 0),
('ky', 'Turkic', 'Kyrgyz', 'Кыргызча - Кыргыз тили', 0, 0),
('lb', 'Indo-European', 'Luxembourgish', 'Lëtzebuergesch', 0, 0),
('lg', 'Niger–Congo', 'Ganda', 'Luganda', 0, 0),
('ln', 'Niger–Congo', 'Lingala', 'Lingála', 0, 0),
('lo', 'Tai–Kadai', 'Lao', 'ພາສາລາວ', 0, 0),
('lt', 'Indo-European', 'Lithuanian', 'lietuvių kalba', 0, 0),
('lu', 'Niger–Congo', 'Luba-Katanga', 'Tshiluba', 0, 0),
('lv', 'Indo-European', 'Latvian', 'latviešu valoda', 0, 0),
('mg', 'Austronesian', 'Malagasy', 'fiteny malagasy', 0, 0),
('mh', 'Austronesian', 'Marshallese', 'Kajin M̧ajeļ', 0, 0),
('mi', 'Austronesian', 'Māori', 'te reo Māori', 0, 0),
('mk', 'Indo-European', 'Macedonian', 'македонски јазик', 0, 0),
('ml', 'Dravidian', 'Malayalam', 'മലയാളം', 0, 0),
('mn', 'Mongolic', 'Mongolian', 'монгол', 0, 0),
('mr', 'Indo-European', 'Marathi (Marāṭhī)', 'मराठी', 0, 0),
('ms', 'Austronesian', 'Malay', 'bahasa Melayu - بهاس ملايو‎', 0, 0),
('mt', 'Afro-Asiatic', 'Maltese', 'Malti', 0, 0),
('na', 'Austronesian', 'Nauru', 'Ekakairũ Naoero', 0, 0),
('nb', 'Indo-European', 'Norwegian Bokmål', 'Norsk bokmål', 0, 0),
('nd', 'Niger–Congo', 'North Ndebele', 'isiNdebele', 0, 0),
('ne', 'Indo-European', 'Nepali', 'नेपाली', 0, 0),
('ng', 'Niger–Congo', 'Ndonga', 'Owambo', 0, 0),
('nl', 'Indo-European', 'Dutch', 'Nederlands - Vlaams', 1, 0),
('nn', 'Indo-European', 'Norwegian Nynorsk', 'Norsk nynorsk', 0, 0),
('no', 'Indo-European', 'Norwegian', 'Norsk', 0, 0),
('nr', 'Niger–Congo', 'South Ndebele', 'isiNdebele', 0, 0),
('nv', 'Dené–Yeniseian', 'Navajo - Navaho', 'Diné bizaad - Dinékʼehǰí', 0, 0),
('ny', 'Niger–Congo', 'Chichewa - Chewa - Nyanja', 'chiCheŵa - chinyanja', 0, 0),
('oc', 'Indo-European', 'Occitan', 'occitan - lenga d''òc', 0, 0),
('oj', 'Algonquian', 'Ojibwe - Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 0, 0),
('om', 'Afro-Asiatic', 'Oromo', 'Afaan Oromoo', 0, 0),
('or', 'India-Asia', 'Oriya', 'ଓଡ଼ିଆ', 0, 0),
('os', 'Indo-European', 'Ossetian - Ossetic', 'ирон æвзаг', 0, 0),
('pa', 'Indo-European', 'Panjabi - Punjabi', 'ਪੰਜਾਬੀ - پنجابی‎', 0, 0),
('pl', 'Indo-European', 'Polish', 'język polski - polszczyzna', 0, 0),
('ps', 'Indo-European', 'Pashto - Pushto', 'پښتو', 0, 0),
('pt', 'Indo-European', 'Portuguese', 'português', 0, 0),
('qu', 'Quechuan', 'Quechua', 'Runa Simi - Kichwa', 0, 0),
('rm', 'Indo-European', 'Romansh', 'rumantsch grischun', 0, 0),
('rn', 'Niger–Congo', 'Kirundi', 'Ikirundi', 0, 0),
('ro', 'Indo-European', 'Romanian', 'limba română', 0, 0),
('ru', 'Indo-European', 'Russian', 'русский язык', 0, 0),
('rw', 'Niger–Congo', 'Kinyarwanda', 'Ikinyarwanda', 0, 0),
('sc', 'Indo-European', 'Sardinian', 'sardu', 0, 0),
('sd', 'Indo-European', 'Sindhi', 'सिन्धी - سنڌي، سندھی‎', 0, 0),
('se', 'Uralic', 'Northern Sami', 'Davvisámegiella', 0, 0),
('sg', 'Creole', 'Sango', 'yângâ tî sängö', 0, 0),
('si', 'Indo-European', 'Sinhala - Sinhalese', 'සිංහල', 0, 0),
('sk', 'Indo-European', 'Slovak', 'slovenčina - slovenský jazyk', 0, 0),
('sl', 'Indo-European', 'Slovene', 'slovenski jezik - slovenščina', 0, 0),
('sm', 'Austronesian', 'Samoan', 'gagana fa''a Samoa', 0, 0),
('sn', 'Niger–Congo', 'Shona', 'chiShona', 0, 0),
('so', 'Afro-Asiatic', 'Somali', 'Soomaaliga - af Soomaali', 0, 0),
('sq', 'Indo-European', 'Albanian', 'gjuha shqipe', 0, 0),
('sr', 'Indo-European', 'Serbian', 'српски језик', 0, 0),
('ss', 'Niger–Congo', 'Swati', 'SiSwati', 0, 0),
('st', 'Niger–Congo', 'Southern Sotho', 'Sesotho', 0, 0),
('su', 'Austronesian', 'Sundanese', 'Basa Sunda', 0, 0),
('sv', 'Indo-European', 'Swedish', 'Svenska', 0, 0),
('sw', 'Niger–Congo', 'Swahili', 'Kiswahili', 0, 0),
('ta', 'Dravidian', 'Tamil', 'தமிழ்', 0, 0),
('te', 'Dravidian', 'Telugu', 'తెలుగు', 0, 0),
('tg', 'Indo-European', 'Tajik', 'тоҷикӣ - toğikī - تاجیکی‎', 0, 0),
('th', 'Tai–Kadai', 'Thai', 'ไทย', 0, 0),
('ti', 'Afro-Asiatic', 'Tigrinya', 'ትግርኛ', 0, 0),
('tk', 'Turkic', 'Turkmen', 'Türkmen - Түркмен', 0, 0),
('tn', 'Niger–Congo', 'Tswana', 'Setswana', 0, 0),
('to', 'Austronesian', 'Tonga (Tonga Islands)', 'faka Tonga', 0, 0),
('tr', 'Turkic', 'Turkish', 'Türkçe', 0, 0),
('ts', 'Niger–Congo', 'Tsonga', 'Xitsonga', 0, 0),
('tt', 'Turkic', 'Tatar', 'татар теле - tatar tele', 0, 0),
('tw', 'Niger–Congo', 'Twi', 'Twi', 0, 0),
('ty', 'Austronesian', 'Tahitian', 'Reo Tahiti', 0, 0),
('ug', 'Turkic', 'Uyghur - Uighur', 'Uyƣurqə - ئۇيغۇرچە‎', 0, 0),
('uk', 'Indo-European', 'Ukrainian', 'українська мова', 0, 0),
('ur', 'Indo-European', 'Urdu', 'اردو', 0, 0),
('uz', 'Turkic', 'Uzbek', 'O‘zbek - Ўзбек - أۇزبېك‎', 0, 0),
('ve', 'Niger–Congo', 'Venda', 'Tshivenḓa', 0, 0),
('vi', 'Austroasiatic', 'Vietnamese', 'Tiếng Việt', 0, 0),
('wo', 'Niger–Congo', 'Wolof', 'Wollof', 0, 0),
('xh', 'Niger–Congo', 'Xhosa', 'isiXhosa', 0, 0),
('yi', 'Indo-European', 'Yiddish', 'ייִדיש', 0, 0),
('yo', 'Niger–Congo', 'Yoruba', 'Yorùbá', 0, 0),
('za', 'Tai–Kadai', 'Zhuang - Chuang', 'Saɯ cueŋƅ - Saw cuengh', 0, 0),
('zh', 'Sino-Tibetan', 'Chinese', '中文 (Zhōngwén) - 汉语 - 漢語', 0, 0),
('zu', 'Niger–Congo', 'Zulu', 'isiZulu', 0, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
