#!/bin/bash

### BEGIN INIT INFO
# Provides:          arduino-hwclock
# Required-Start:    $network $named $time $local_fs kmod fake-hwclock ntp
# Required-Stop:     $network $named $time $local_fs kmod fake-hwclock ntp
# Should-Stop:       
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Restore / save the current clock using Arduino's internal millis counter
# Description:       
### END INIT INFO

set -e

P2PFOODLAB_UPDATE="/var/p2pfoodlab/bin/p2pfoodlab-update"

save_date() {
    $P2PFOODLAB_UPDATE update-clock
}

restore_date() {
    $P2PFOODLAB_UPDATE set-clock
}

case "${1:-}" in
  stop|reload|restart|force-reload)
        echo "Stopping arduino hwclock: saving system time."
        save_date;;

  start)
        echo "Starting arduino hwclock: loading system time."
        restore_date ;;

  *)
        echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
