#! /bin/bash
### BEGIN INIT INFO
# Provides:          p2pfoodlab-init
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:   
# X-Start-Before:    hostname    
# Default-Start:     S
# Default-Stop:      
# Short-Description: Updates system files for P2P Food Lab sensorbox 
# Description:
### END INIT INFO

set -e 

log_message() {
    echo $1 >> /var/p2pfoodlab/log.txt
}

do_start() {
    log_message "[p2pfoodlab] Info: Updating P2P Food Lab configuration files" 
    /var/p2pfoodlab/bin/sensorbox generate-system-files
}

do_stop() {
    do_stop_daemon
}

case "$1" in
start)
        do_start
        ;;
stop)
	do_stop
	;;
restart|reload|force-reload)
	do_start
	;;
force-start)
	do_start
	;;
*)
	echo "Usage: p2pfoodlab-init {start|stop|restart|reload|force-reload|force-start}"
	exit 1
	;;
esac
